// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsDyqdAZReqlJBEbWGj080-DMvaHA6XNc',
    appId: '1:7355723931:web:336c40fc75ca4ea88d563e',
    messagingSenderId: '7355723931',
    projectId: 'blog-app-task-4e492',
    authDomain: 'blog-app-task-4e492.firebaseapp.com',
    storageBucket: 'blog-app-task-4e492.firebasestorage.app',
    measurementId: 'G-ETG1TM1KPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ77gF0U4E2YxAUvuenYohwNRzRIO5p_Q',
    appId: '1:7355723931:android:e77bddbb367b36a58d563e',
    messagingSenderId: '7355723931',
    projectId: 'blog-app-task-4e492',
    storageBucket: 'blog-app-task-4e492.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKNcDOoyfA9riD3sP5NHU2260Za8zs6vM',
    appId: '1:7355723931:ios:d88d94456e3b5c788d563e',
    messagingSenderId: '7355723931',
    projectId: 'blog-app-task-4e492',
    storageBucket: 'blog-app-task-4e492.firebasestorage.app',
    iosBundleId: 'com.example.blogAppTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKNcDOoyfA9riD3sP5NHU2260Za8zs6vM',
    appId: '1:7355723931:ios:d88d94456e3b5c788d563e',
    messagingSenderId: '7355723931',
    projectId: 'blog-app-task-4e492',
    storageBucket: 'blog-app-task-4e492.firebasestorage.app',
    iosBundleId: 'com.example.blogAppTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsDyqdAZReqlJBEbWGj080-DMvaHA6XNc',
    appId: '1:7355723931:web:78cb64fcb0581a958d563e',
    messagingSenderId: '7355723931',
    projectId: 'blog-app-task-4e492',
    authDomain: 'blog-app-task-4e492.firebaseapp.com',
    storageBucket: 'blog-app-task-4e492.firebasestorage.app',
    measurementId: 'G-T9CJ7EK3L6',
  );
}
